branch-defaults:
  master:
    environment: production
global:
  application_name: paypal-docker
  default_ec2_keyname: null
  default_platform: Docker 1.9.1
  default_region: us-east-1
  profile: null
  sc: git
